modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
description='''
Example cross-loader mod metadata.
'''

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="forge"
mandatory=false
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="neoforge"
mandatory=false
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"
